# Generated by Django 6.0.8 on 2026-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="county_of_origin",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="county of origin"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_personalizable",
            field=models.BooleanField(default=False, verbose_name="is personalizable"),
        ),
        migrations.AddField(
            model_name="listing",
            name="personalization_instructions",
            field=models.TextField(
                blank=True,
                help_text="Instructions for buyer custom text, e.g. Enter name to engrave",
                verbose_name="personalization instructions",
            ),
        ),
    ]
