# Generated by Django 5.2.17 on 2026-08-10 13:12

from django.db import migrations, models
from django.db.models import Count


def clamp_inventory_reserved(apps, schema_editor):
    """Clamp reserved qty so CheckConstraint can be applied to existing rows."""
    Inventory = apps.get_model('listings', 'Inventory')
    for inv in Inventory.objects.all():
        if inv.quantity_reserved > inv.quantity_available:
            inv.quantity_reserved = inv.quantity_available
            inv.save(update_fields=['quantity_reserved'])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_shipping_profile'),
    ]

    operations = [
        migrations.RunPython(clamp_inventory_reserved, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('quantity_reserved__lte', models.F('quantity_available'))
                ),
                name='inventory_reserved_lte_available',
            ),
        ),
    ]
