# Generated by Django 5.2.17 on 2026-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("listings", "0009_cart_inventory_constraints"),
        ("shipping", "0003_shipping_profiles"),
        ("shops", "0007_shop_gift_approval_status_shop_gift_request_notes_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "base_price"], name="listings_li_status_e3e7c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "-published_at"], name="listings_li_status_477a45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "category", "-published_at"],
                name="listings_li_status_f760d1_idx",
            ),
        ),
    ]
