# Generated by Django 6.0.8 on 2026-08-05 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=64, verbose_name="icon"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="image"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="position"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="SEO title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="SEO description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["position", "name"],
            },
        ),
    ]
