# Generated by Django 6.0.8 on 2026-08-05 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=100, verbose_name="recipient name"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone number")),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city_or_town",
                    models.CharField(max_length=100, verbose_name="city or town"),
                ),
                (
                    "county",
                    models.CharField(
                        default="Nairobi", max_length=100, verbose_name="county"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Kenya", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "is_default_shipping",
                    models.BooleanField(
                        default=False, verbose_name="default shipping address"
                    ),
                ),
                (
                    "is_default_billing",
                    models.BooleanField(
                        default=False, verbose_name="default billing address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ["-is_default_shipping", "-created_at"],
            },
        ),
    ]
