# Generated by Django 6.0.8 on 2026-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="sub_county",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="sub county"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="village",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="village / landmark"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="ward",
            field=models.CharField(blank=True, max_length=100, verbose_name="ward"),
        ),
    ]
