# Generated by Django 5.2.17 on 2026-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_buyer_protection"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("online", "Online (provider)"),
                    ("whatsapp", "Arranged on WhatsApp"),
                ],
                default="online",
                max_length=20,
            ),
        ),
    ]
