# Generated by Django 5.2.17 on 2026-09-10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_uniq_confirmed_payment_per_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCallbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('authenticated', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                (
                    'outcome',
                    models.CharField(
                        choices=[('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected')],
                        default='received',
                        max_length=20,
                    ),
                ),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'payment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='callback_events',
                        to='payments.payment',
                    ),
                ),
            ],
            options={'ordering': ['-received_at']},
        ),
    ]
