# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_preferences_and_delivery_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
