# Generated by Django 5.2.17 on 2026-08-10 11:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0008_listing_shipping_profile"),
        ("shops", "0006_seller_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingDailyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("listing_uuid", models.UUIDField(db_index=True)),
                ("title_snapshot", models.CharField(max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("units_sold", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_metrics",
                        to="listings.listing",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_daily_metrics",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-units_sold"],
                "indexes": [
                    models.Index(fields=["shop", "date"], name="analytics_lday_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "listing_uuid", "date"),
                        name="uniq_listing_daily_metric",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopDailyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("orders", models.PositiveIntegerField(default=0)),
                ("units_sold", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("followers", models.PositiveIntegerField(default=0)),
                ("listing_saves", models.PositiveIntegerField(default=0)),
                ("returning_viewers", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["shop", "date"], name="analytics_sday_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "date"), name="uniq_shop_daily_metric"
                    )
                ],
            },
        ),
    ]
