# Generated by Django 6.0.8 on 2026-08-05 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="shop name")),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="slug"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="shops/logos/", verbose_name="logo"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, upload_to="shops/banners/", verbose_name="banner"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "county",
                    models.CharField(
                        default="Nairobi", max_length=100, verbose_name="county"
                    ),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                (
                    "rating_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="rating average",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(default=0, verbose_name="rating count"),
                ),
                (
                    "policies",
                    models.TextField(blank=True, verbose_name="shop policies"),
                ),
                (
                    "vacation_mode",
                    models.BooleanField(default=False, verbose_name="vacation mode"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "shop",
                "verbose_name_plural": "shops",
                "ordering": ["name"],
            },
        ),
    ]
