# Generated by Django 5.2.17 on 2026-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_seller_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="gift_approval_status",
            field=models.CharField(
                choices=[
                    ("unrequested", "Unrequested"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="unrequested",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="gift_request_notes",
            field=models.TextField(blank=True, verbose_name="gift request notes"),
        ),
        migrations.AddField(
            model_name="shop",
            name="is_promoted",
            field=models.BooleanField(default=False, verbose_name="promoted shop"),
        ),
    ]
