# Generated by Django 5.2.17 on 2026-08-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_shop_gift_approval_status_shop_gift_request_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_local_seller",
            field=models.BooleanField(default=True, verbose_name="Ziuza Local seller"),
        ),
        migrations.AddField(
            model_name="shop",
            name="local_delivery_scope",
            field=models.CharField(
                choices=[
                    ("ward", "Ward only"),
                    ("sub_county", "Sub-County"),
                    ("county", "Entire County"),
                    ("nationwide", "Nationwide with local pickup"),
                ],
                default="county",
                max_length=20,
                verbose_name="local delivery scope",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="local_pickup_available",
            field=models.BooleanField(default=True, verbose_name="offers local pickup"),
        ),
        migrations.AddField(
            model_name="shop",
            name="local_pickup_instructions",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="local pickup details / landmark",
            ),
        ),
    ]
