# Generated by Django 5.2.17 on 2026-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_shop_is_local_seller_shop_local_delivery_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="International digits without +, e.g. 254712345678. Enables WhatsApp checkout.",
                max_length=20,
                verbose_name="WhatsApp number",
            ),
        ),
    ]
