# Generated by Django 6.0.8 on 2026-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="personalization_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
