# Generated by Django 5.2.17 on 2026-08-10 13:12

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def _merge_cart_items(apps, keeper, duplicate):
    CartItem = apps.get_model('cart', 'CartItem')
    for item in CartItem.objects.filter(cart=duplicate):
        if item.variant_id is None:
            existing = CartItem.objects.filter(
                cart=keeper,
                listing_id=item.listing_id,
                variant__isnull=True,
                personalization_signature=item.personalization_signature,
            ).first()
        else:
            existing = CartItem.objects.filter(
                cart=keeper,
                listing_id=item.listing_id,
                variant_id=item.variant_id,
                personalization_signature=item.personalization_signature,
            ).first()
        if existing:
            existing.quantity += item.quantity
            existing.save(update_fields=['quantity'])
            item.delete()
        else:
            item.cart = keeper
            item.save(update_fields=['cart'])


def dedupe_carts(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    user_ids = (
        Cart.objects.filter(user__isnull=False)
        .values('user_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
        .values_list('user_id', flat=True)
    )
    for user_id in user_ids:
        carts = list(Cart.objects.filter(user_id=user_id).order_by('-updated_at', '-created_at'))
        keeper = carts[0]
        for duplicate in carts[1:]:
            _merge_cart_items(apps, keeper, duplicate)
            duplicate.delete()

    session_keys = (
        Cart.objects.filter(user__isnull=True)
        .exclude(session_key='')
        .values('session_key')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
        .values_list('session_key', flat=True)
    )
    for session_key in session_keys:
        carts = list(
            Cart.objects.filter(user__isnull=True, session_key=session_key).order_by(
                '-updated_at', '-created_at'
            )
        )
        keeper = carts[0]
        for duplicate in carts[1:]:
            _merge_cart_items(apps, keeper, duplicate)
            duplicate.delete()


def dedupe_cartitems(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')

    base_groups = (
        CartItem.objects.filter(variant__isnull=True)
        .values('cart_id', 'listing_id', 'personalization_signature')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for group in base_groups:
        items = list(
            CartItem.objects.filter(
                cart_id=group['cart_id'],
                listing_id=group['listing_id'],
                personalization_signature=group['personalization_signature'],
                variant__isnull=True,
            ).order_by('created_at')
        )
        keeper = items[0]
        keeper.quantity = sum(i.quantity for i in items)
        keeper.save(update_fields=['quantity'])
        for duplicate in items[1:]:
            duplicate.delete()

    variant_groups = (
        CartItem.objects.filter(variant__isnull=False)
        .values('cart_id', 'listing_id', 'variant_id', 'personalization_signature')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for group in variant_groups:
        items = list(
            CartItem.objects.filter(
                cart_id=group['cart_id'],
                listing_id=group['listing_id'],
                variant_id=group['variant_id'],
                personalization_signature=group['personalization_signature'],
            ).order_by('created_at')
        )
        keeper = items[0]
        keeper.quantity = sum(i.quantity for i in items)
        keeper.save(update_fields=['quantity'])
        for duplicate in items[1:]:
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_structured_personalization'),
        ('listings', '0009_cart_inventory_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_carts, migrations.RunPython.noop),
        migrations.RunPython(dedupe_cartitems, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False)),
                fields=('user',),
                name='uniq_cart_per_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('user__isnull', True), models.Q(('session_key', ''), _negated=True)
                ),
                fields=('session_key',),
                name='uniq_anon_cart_per_session',
            ),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(('variant__isnull', True)),
                fields=('cart', 'listing', 'personalization_signature'),
                name='uniq_cartitem_base_variant',
            ),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(('variant__isnull', False)),
                fields=('cart', 'listing', 'variant', 'personalization_signature'),
                name='uniq_cartitem_with_variant',
            ),
        ),
    ]
