# Generated by Django 6.0.8 on 2026-08-05 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="cms/collections/")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("desktop_image", models.ImageField(blank=True, upload_to="cms/hero/")),
                ("mobile_image", models.ImageField(blank=True, upload_to="cms/hero/")),
                ("primary_cta_label", models.CharField(blank=True, max_length=80)),
                ("primary_cta_url", models.CharField(blank=True, max_length=255)),
                ("secondary_cta_label", models.CharField(blank=True, max_length=80)),
                ("secondary_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "background_configuration",
                    models.JSONField(blank=True, default=dict),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("featured_listings", "Featured listings"),
                            ("featured_shops", "Featured shops"),
                            ("categories", "Categories"),
                            ("collections", "Collections"),
                            ("trust", "Trust"),
                            ("custom", "Custom"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "title"],
            },
        ),
        migrations.CreateModel(
            name="CollectionListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.collection",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("collection", "listing")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="listings",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="content.CollectionListing",
                to="listings.listing",
            ),
        ),
    ]
