# Generated by Django 5.2.17 on 2026-08-10 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroPromoCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Ziuza Picks", max_length=160, verbose_name="title"
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        default="Curated Selection",
                        max_length=80,
                        verbose_name="badge text",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Handpicked collections just for you.",
                        max_length=255,
                        verbose_name="subtitle",
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        default="Explore Picks",
                        max_length=80,
                        verbose_name="button label",
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        default="/picks/", max_length=255, verbose_name="button URL"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#00482B",
                        max_length=30,
                        verbose_name="background color",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#C8102E",
                        max_length=30,
                        verbose_name="accent bar color",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/promo/",
                        verbose_name="custom promo image",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="priority"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="starts at"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ends at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "hero promo card",
                "verbose_name_plural": "hero promo cards",
                "ordering": ["priority", "-updated_at"],
            },
        ),
    ]
