# Generated by Django 5.2.17 on 2026-08-15 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_rename_ziuza_picks_to_maridadis"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBannerAd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=160, verbose_name="banner title / campaign"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload animated GIF, PNG, or WebP banner (e.g. 1200x120px)",
                        upload_to="cms/banners/",
                        verbose_name="banner image / GIF",
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        default="/local/",
                        help_text="Destination URL when banner is clicked",
                        max_length=255,
                        verbose_name="target URL",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility description for the banner",
                        max_length=200,
                        verbose_name="alt text",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="priority"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="starts at"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ends at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "promotional banner ad",
                "verbose_name_plural": "promotional banner ads",
                "ordering": ["priority", "-updated_at"],
            },
        ),
    ]
