# Generated by Django 5.2.17 on 2026-08-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_promobannerad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("promo_banner", "Promotional banner"),
                    ("featured_listings", "Featured listings"),
                    ("featured_shops", "Featured shops"),
                    ("categories", "Categories"),
                    ("collections", "Collections"),
                    ("trust", "Trust"),
                    ("custom", "Custom"),
                ],
                max_length=40,
            ),
        ),
    ]
